applications/home/urls.py
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path('home/', views.IndexView.as_view()),
    path('about/', views.AboutView.as_view(), name='about'),
    path('lista/', views.PrurbaListView.as_view()),
    path('lista_prueba/', views.ModeloPruebaListView.as_view()),
    path('add_prue/', views.PruebaCreateView.as_view(), name='prueba_add'),
    path(
        'resumen-foundation/', 
        views.ResumenFoundationView.as_view(), 
        name='Resumen_foundation'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Incluimos las url de mis app
    path('', include('applications.home.urls')),
    path('', include('applications.empleado.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/models.py
from django.db import models

class Prueba(models.Model):
    titulo = models.CharField(max_length=30)
    subtitulo = models.CharField(max_length=50)
    cantidad = models.IntegerField()

    def __str__(self):
        return self.titulo + '-' + self.subtitulo

applications/home/forms.py
from django import forms
from .models import Prueba
 
class PruebaForm(forms.ModelForm):
    """Form definition for Prueba."""

    class Meta:
        """Meta definition for Pruebaform."""

        model = Prueba
        fields = (
            'titulo', 
            'subtitulo',
            'cantidad',
        )
        
        widgets = {
            'titulo': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese texto aqui'
                }
            )
        }
    def clean_cantidad(self):
        cantidad = self.cleaned_data.get('cantidad')
    
    
        if cantidad < 10:
            raise forms.ValidationError('Ingrese un numero mayor a 10')
    
        return cantidad

applications/home/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView, 
    ListView, 
    CreateView
)
from .models import Prueba
# Create your views here.

from .forms import PruebaForm

class AboutView(TemplateView):
    template_name = "home/about.html"

class IndexView(TemplateView):
    template_name = "home/home.html"

 
class ResumenFoundationView(TemplateView):
    template_name = "home/resume_foundation.html"

class PrurbaListView(ListView):
    template_name = "home/lista.html"
    queryset = ['C', 'B', 'C']
    context_object_name = 'lista_prueba'


class ModeloPruebaListView(ListView):
    model = Prueba
    template_name = "home/pruebas.html"
    context_object_name = 'lista_prueba'


class PruebaCreateView(CreateView):
    model = Prueba
    template_name = "home/add.html"
    form_class = PruebaForm
    success_url = '/'

templates/home/about.html
<h1>Hola hola</h1>

templates/home/add.html
<h2>Probando CreateView</h2>

<form method="POST">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Guardar</button>
</form>

templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
</head>
<body>
    <h1 class="ejemplo1">Hola desde la carpeta template</h1>
    <h3 class="ejemplo2">Probando el padron de diseno</h3>
    <a href="{% url 'home_app:about' %}" class="submit button">Learn More</a>
<a href="#features" class="button">View All Features</a>

<!-- Buttons (actions) -->
<button class="submit success button">Save</button>
<button type="button" class="alert button">Delete</button>
</body>
</html>

templates/home/lista.html
<h1>lista de prueba</h1>

{{ lista_prueba }}

templates/home/pruebas.html
<h1>listando elementos de una bd</h1>

{{ lista_prueba }}

<ul>
    
    {% for prueba in lista_prueba %}
        <li>{{ prueba.titulo }}</li>
    {% endfor %}
        
</ul>

templates/home/resume_foundation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>Resumen de Foundation</h1>
    <div class="grid-x" style="border: 1px solid green;">
        <h2 class="cell small-12 large-5 " style="border: 1px solid red;">Elemento1</h2>
        <h2 class="cell large-4 " style="border: 1px solid black;">Elemento2</h2>
        <h2 class="cell large-3" style="border: 1px solid blue;">Elemento3</h2>
        <div class="grid-x large-6" style="border: 1px solid grey;">
            <h4 class="cell large-1">otro1</h4>
            <h4 class="cell large-1">otro2</h4>
            <h4 class="cell large-1">otro elemento 3</h4>
        </div>
    </div>
</body>
</html>