applications/departamento/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'lista-depa/', 
        views.DepartamentoListView.as_view(), 
        name='dep_lista'
    ),
    path(
        'new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_depa'
    )
]

applications/empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleado_all'
    ),
    path(
        'listar_by_area/<shorname>/', 
        views.ListByAreaEmpleado.as_view(),
        name = 'empleados_elarea'
    ),
    path(
        'listar_empadmin/', 
        views.ListaEmpleadosAdnmin.as_view(),
        name = 'empleados_admin'
    ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadosByKword.as_view()
    ),
    path(
        'Lista_habilidades/', 
         views.ListHabilidadesEmpleado.as_view()
    ),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name = 'empleado_add'
    ),
    path(
        'succes/', 
        views.SuccesView.as_view(), 
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
    path(
        'succes2/', 
        views.Succes2View.as_view(), 
        name='eliminar_empleado'
    ),

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Incluimos las url de mis app
    path('', include('applications.home.urls')),
    path('', include('applications.empleado.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>
        
        {% block title %}
            
        {% endblock title %}
            
    </title>
</head>
<body>
    
    {% block content %}
        
    {% endblock content %}

    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
        
</body>
</html>

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'persona_app:empleado_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:dep_lista' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_depa' %}">Nuevo Departamentos</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleados"></li>
        <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>