applications/departamento/urls.py
#from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'lista-depa/', 
        views.DepartamentoListView.as_view(), 
        name='dep_lista'
    ),
    path(
        'new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_depa'
    )
]

applications/empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleado_all'
    ),
    path(
        'listar_by_area/<shorname>/', 
        views.ListByAreaEmpleado.as_view(),
        name = 'empleados_elarea'
    ),
    path(
        'listar_empadmin/', 
        views.ListaEmpleadosAdnmin.as_view(),
        name = 'empleados_admin'
    ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadosByKword.as_view()
    ),
    path(
        'Lista_habilidades/', 
         views.ListHabilidadesEmpleado.as_view()
    ),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name = 'empleado_add'
    ),
    path(
        'succes/', 
        views.SuccesView.as_view(), 
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
    path(
        'succes2/', 
        views.Succes2View.as_view(), 
        name='eliminar_empleado'
    ),

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Incluimos las url de mis app
    path('', include('applications.home.urls')),
    path('', include('applications.empleado.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombr Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    """ Personalizando un poco mi admin con la clase meta"""
    class Meta:
        verbose_name = 'Mi Departamento' 
        verbose_name_plural = 'Area de las Empresas' 
        ordering = ['-name']
        unique_together = ('name', 'shor_name') # Para que no se repita esta combinacion de elementos


    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    """FORMNAME definition."""

    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

applications/departamento/views.py
#from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from applications.empleado.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = 'depa'


#Formulario que no depende de un modelo
class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('*****Estamos en el form valid*******')

        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellidos,
            job='1',
            departamento=depa        
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'includes/base.html' %}


{% block title %}
    Lista Departamentos
{% endblock title %}
    


{% block content %}
{% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos de la Empresa</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamento in depa %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shor_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_elarea' departamento.shor_name %}">Ver empleados</a>
                            </td>
                        </tr>  
                        {% endfor %}
                            
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/departamento/new_departamento.html
{% extends 'includes/base.html' %}


{% block title %}
    Registrar Departamento
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Registrar Departamento
        </h1>

        <form class="cell grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="cell large-6">
                <label>Nombres
                    {{ form.nombre }}
                </label>
            </div>
            <div class="cell large-6">
                    <label>Apellidos
                    {{ form.nombre }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Trabajo
                    {{ form.nombre }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Departamento
                    {{ form.nombre }}
                </label>
            </div>
            <div class="cell large-6">
                <label>shorname
                    {{ form.nombre }}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="button success">Guardar</button>
            </div> 
        </form>
    </div>
</div>

{% endblock content %}