applications/empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleado_all'
    ),
    path(
        'listar_by_area/<shorname>/', 
        views.ListByAreaEmpleado.as_view(),
        name = 'empleados_elarea'
    ),
    path(
        'listar_empadmin/', 
        views.ListaEmpleadosAdnmin.as_view(),
        name = 'empleados_admin'
    ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadosByKword.as_view()
    ),
    path(
        'Lista_habilidades/', 
         views.ListHabilidadesEmpleado.as_view()
    ),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name = 'empleado_add'
    ),
    path(
        'succes/', 
        views.SuccesView.as_view(), 
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
    path(
        'succes2/', 
        views.Succes2View.as_view(), 
        name='eliminar_empleado'
    ),

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Incluimos las url de mis app
    path('', include('applications.home.urls')),
    path('', include('applications.empleado.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleado/models.py
from django.db import models
from applications.departamento.models import Departamento
#from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class meta:
        verbose_name = 'Habilidad' 
        verbose_name_plural = 'Habilidades Empleados'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad
    

# Create your models here.
class Empleado(models.Model):
    """Modelo para tabla empleado"""

    JOB_CHOICE = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )

    # Contador
    # Administrador
    # Economista
    # Otros

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=50)
    full_name = models.CharField(
        'Nombres Completos', 
        max_length=120,
    )
    job = models.CharField('Trabajos', max_length=1, choices=JOB_CHOICE)

    # ForeingKey ---> Relacion de uno a uno"
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)


    #ImageField ---> Lo veremos luego
    avatar_emp = models.ImageField(upload_to='media_empleados', blank=True, null=True)

    #  ---> Relacion de mucho a mucho
    habilidades = models.ManyToManyField(Habilidades)

    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-first_name', 'last_name']
        unique_together = ['first_name', 'departamento']

    #hoja_vida = RichTextField()


    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

applications/empleado/forms.py
from django import forms

from . models import Empleado



class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields =(
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar_emp',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/empleado/views.py
# from typing import Any, Dict, Optional
# from django.db.models.query import QuerySet
# from django.forms.models import BaseModelForm
# from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)

#Si vamos a trabajar con un listView este nos pide un queriset o modelo por tanto
#Modelo
from .models import Empleado
#Form
from .forms import EmpleadoForm

class InicioView(TemplateView):
    #vista que carga la pagina de inicio
    template_name = "inicio.html" 



# 1.- Listar todos los empleados de la empresa
# 2.- Listar todos los empleados que pertenecen a un area de la empresa
# 3.- Listar empleados por trabajo 
# 4.- Listar los empleados por palabra clave
# 5.- Listar abilidades de un empleado

# 1. 
class ListAllEmpleados(ListView):
    template_name = 'empleado/list_all.html'
    #Paginacion
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        print('========', palabra_clave)
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave
        )
        return lista

class ListaEmpleadosAdnmin(ListView):
    template_name = 'empleado/list_admin.html'
    #Paginacion
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado
    

    #Que pasa si no le pongo esta forma de acceder
    #context_object_name = 'lista'

    #veamos otra forma


#2. queryset

class ListByAreaEmpleado(ListView):
    """Lista empleado de un area"""
    template_name = 'empleado/lista_by_area.html'
    context_object_name = 'empleados'

    #usando un filto entrandolo del codigo
    """queryset = Empleado.objects.filter(
        departamento__shor_name = 'contabilidad' 
    )"""

    def get_queryset(self):
        #El codigo que quiera
        #Usando un filtro a travez de una url
        elarea = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name = elarea 
        )
        return lista
    
    #veamos un filtro a travez de una caja de texto

    #4.

class ListEmpleadosByKword(ListView):
    """Lista empleado por palabra clave a traves de caja de texto"""
    template_name = 'empleado/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('************')
        palabra_clave = self.request.GET.get("kword", '')
        #print('========', palabra_clave)
        lista = Empleado.objects.filter(
            first_name = palabra_clave 
        )
        return lista
    
#5.Listar  habilidades de un empleado

class ListHabilidadesEmpleado(ListView):
    template_name = 'empleado/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=5)
        #print(empleado.habilidades.all())
        return empleado.habilidades.all()
    
#detailView


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "empleado/detail_empleado.html"

    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        #Todo un proceso
        context['titulo'] = 'Empleado del mes'
        return context
    

class SuccesView(TemplateView):
    template_name = "empleado/succes.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "empleado/add.html"
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        #Logica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)



class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "empleado/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('**********MetodoPOST*********')
        print('*******************')
        print('++++++++++++++++')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        #Logica del proceso
        print('**********MetodoFROM_VALID*********')
        print('*******************')
        return super(EmpleadoUpdateView, self).form_valid(form)
    
class Succes2View(TemplateView):
    template_name = "empleado/succes2.html"

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "empleado/delete.html"
    success_url = reverse_lazy('persona_app:empleados_admin')

templates/empleado/add.html

{% extends 'includes/base.html' %}


{% block title %}
    Registro de empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Registrar empleado
        </h1>

        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="cell large-6">
                <label>Nombres
                    {{ form.first_name }}
                </label>
            </div>
            <div class="cell large-6">
                    <label>Apellidos
                    {{ form.last_name }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Trabajo
                    {{ form.job }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Departamento
                    {{ form.departamento }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Habilidades extra
                    {{ form.habilidades }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Foto
                    {{ form.avatar_emp }}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="button success">Guardar</button>
            </div> 
        </form>
    </div>
</div>

{% endblock content %}




templates/empleado/by_kword.html
<h1>Buscar empleado por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nomre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>
<ul>
    
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

templates/empleado/delete.html
{% extends 'includes/base.html' %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            ELIMINAR EMPLEADO: {{ object.full_name }}
        </h1>
        <div class="cell">
            <form class="cell" method="post">{% csrf_token %}
                <div class="alert callout">
                    <h5>Desea eliminar este empleado?</h5>
                    <p>Una ves eliminado este empleado no podra acceder a su ficha!!!</p>
                    <button type="submit" class="alert button">Confirmar</button>
                  </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/empleado/detail_empleado.html
{% extends 'includes/base.html' %}

{% load static %}

{% block title %}
    {{ object.full_name }}
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
              {{ empleado.get_job_display }}
            </div>
            
            {% if empleado.avatar_emp %}
                <img src="{{ empleado.avatar_emp.url }}">
            {% else %}
                <img src="{% static 'img/img1.jpg' %}">
            {% endif %}
                
            
            <div class="card-section">
              <h4>{{ empleado.full_name }}</h4>
              <h4>{{ empleado.last_name }}</h4>
              <h4>{{ empleado.departamento.shor_name }}</h4>
              <p><span class="label">Habilidades:</span></p>
              <ul class="vertical menu">
                
                {% for h in empleado.habilidades.all %}
                    <li>{{ h.habilidad }}</li>
                {% endfor %}

              </ul>
            </div>
          </div>
    </div>
</div>

{% endblock content %}



templates/empleado/habilidades.html
<h1>Habilidades de empleado</h1>

<ul>
    
    {% for h in habilidades %}
        <li>{{h}}</li>
    {% endfor %}
        
</ul>

templates/empleado/list_admin.html
{% extends 'includes/base.html' %}

{% block title %}
    Listar Empleados
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Lista Empleados
        </h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTOS</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras<span class="show-for-sr"></span></a>
                    </li>
                    {% endif %}
    
                    {% for pagina in paginator.page_range %}

                    
                    {% if pagina == page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>  
                    {% endif %}
                        
                    
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente<span class="show-for-sr">page</span></a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>    
{% endblock content %}

templates/empleado/list_all.html
{% extends 'includes/base.html' %}

{% block title %}
    Listar Empleados
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Lista Empleados
        </h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">                   
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>                    
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTOS</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras<span class="show-for-sr"></span></a>
                    </li>
                    {% endif %}
    
                    {% for pagina in paginator.page_range %}

                    
                    {% if pagina == page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                    {% else %}
                    <li><a href="?page={{pagina}}">{{ pagina }}</a></li>  
                    {% endif %}
                        
                    
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente<span class="show-for-sr">page</span></a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>    
{% endblock content %}

templates/empleado/lista_by_area.html
{% extends 'includes/base.html' %}


{% block title %}
    Lista empleados por  Departamentos
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">Empleados por area</div>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTOS</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

<h1>Esta es la listab empleado por departamento</h1>

{{object_list}}

<ul>
    
    {% for e in object_list %}
       <li> {{e}}</li>
    {% endfor %}
        
</ul>

templates/empleado/succes.html
<h1>Felicidades, se guardo correctamente el empleado</h1>

templates/empleado/succes2.html
<h1>se a eliminado corectamente</h1>

templates/empleado/update.html
{% extends 'includes/base.html' %}


{% block title %}
    Editar empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleados
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x " method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades extra
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell">
                    <button class="submit success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock content %}

